services:
  skorbord:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skorbord
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
    volumes:
      - ./server/data/db.json:/app/server/data/db.json
      - ./public/uploads/badges:/app/public/uploads/badges
    restart: unless-stopped
